# -*- coding: utf-8 -*-
"""img_upload_working.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WY-HtFC_SjCjFKoTRafXSqjzwApFJvRU
"""

!pip install flask-ngrok

from flask import Flask , render_template, request
from flask_ngrok import run_with_ngrok
from os.path import join as pathJoin
from os.path import getsize as fSize
import os

app=Flask(__name__)
app.config['SECRET_KEY']="Dhusss Shala"
app.config['IMAGE_UPLOAD']="/content/static/uploaded_images"
path_to_img=app.config['IMAGE_UPLOAD']
run_with_ngrok(app)

@app.route('/',methods=["POST","GET"])
def index_upload():
  if request.method=="POST":
    k=False
    if request.files and request.files['myImage'].filename != '' :
      filename=request.files['myImage']
      print(filename)
      filename.save(pathJoin(app.config['IMAGE_UPLOAD'],filename.filename))
      k=True
      path="../static/uploaded_images"
      path=pathJoin(path,filename.filename)
      #path="../static/uploaded_images/"
      return render_template("img.html",fileName=path)
      #return render_template("index.html",val=k,msg="Plz Upload Again",sz=fSize(pathJoin(app.config['IMAGE_UPLOAD'],filename.filename))//(1024*1024))
    else:
      k=False
      
      return render_template("index.html",val=k,msg="Plz Upload Again" , sz=0)
      #return render_template("img.html",fileName=path)
  else:
    return render_template('index.html',msg="Upload The Image",sz=0)
"""
@app.route("/showImg")
def show_img(filename):
    path=pathJoin(app.config['IMAGE_UPLOAD'],filename)
    render_template('img.html',fileName=path)
"""

if __name__=="__main__":
  app.run()
  #os.rmdir(pathJoin(path_to_img))

